export const GET_PRODUCTOS = 'GET_PRODUCTOS'

export const SELECT_PRODUCTO = 'SELECT_PRODUCTO'

export const CONFIRM_ORDEN_PLATILLO = 'CONFIRM_ORDEN_PLATILLO'

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'

export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO'

export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'
